[package]
name = "clean-arch"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
mockall = "0.13.0"
thiserror = "1.0.64"

[dependencies.serde]
version = "1.0.210"
features = ["derive"]

[dependencies.clap]
version = "4.5.19"
features = ["derive"]

[dependencies.uuid]
version = "1.10.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "serde",             # Enable Serilize and Deserialize derive
]

