[package]
name = "clean-arch"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "clean-arch"
path = "src/bin/cli-json-file.rs"

[workspace]
members = [
    "crates/adapter",
    "crates/application",
    "crates/domain",
    "crates/infrastructure",
]
exclude = ["crates/web-app"]

[workspace.package]
authors = ["Filip Dulic <filip.dulic@gmail.com>"]
version = "0.1.0"
edition = "2021"
rust-version = "1.79"

[dependencies]
# Workspace dependencies
ca-infrastructure = "0.1.0"
# External dependencies
clap = { version = "4.5", features = ["derive"] }

[patch.crates-io]
ca-adapter = { path = "crates/adapter" }
ca-application = { path = "crates/application" }
ca-domain = { path = "crates/domain" }
ca-infrastructure = { path = "crates/infrastructure" }
