[package]
name = "ca-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
ca-domain = "0.1.0"

# External dependencies
log = "0.4"
thiserror = "1.0"
