[package]
name = "ca-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
ca-domain = { version = "=0.1.0", path = "../domain" }

chrono.workspace = true
log.workspace = true
thiserror.workspace = true
serde.workspace = true
validator.workspace = true
async-trait.workspace = true

# Dev dependencies
[dev-dependencies]
mockall.workspace = true
rstest.workspace = true
tokio.workspace = true
uuid.workspace = true
