[package]
name = "ca-infrastructure-boundary-poem-openapi"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
ca-adapter = { version = "=0.1.0", path = "../../../adapter" }
ca-application = { version = "=0.1.0", path = "../../../application" }
ca-domain = { version = "=0.1.0", path = "../../../domain" }

# External dependencies
uuid.workspace = true
poem-openapi.workspace = true
async-trait.workspace = true
chrono.workspace = true
