[package]
name = "ca-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
uuid = { version = "1.16.0", features = ["v4"] }
chrono = "0.4.40"

[dev-dependencies]
rstest = "0.25.0"
