[package]
name = "ca-domain"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
# Workspace dependencies
uuid = { version = "1.11.0", features = ["v4"] }
chrono = "0.4.38"

[dev-dependencies]
rstest = "0.23.0"
